### ISSUE TITLE
I thought the symtseries lib was going to be statically linked into the Lua wrapper .so

### ISSUE THREAD

**Issue by trink** [Quadrocube/symtseries#15]
The library is pretty small so it would be nice to get rid of the extra dependency

ldd modules/sax.so 
    linux-vdso.so.1 =>  (0x00007ffe82340000)
    libluasb.so.0 => /usr/lib/libluasb.so.0 (0x00007f009c544000)
    libluasandbox.so.0 => /usr/lib/libluasandbox.so.0 (0x00007f009c33a000)
    **libsymtseries.so => /usr/local/lib/libsymtseries.so (0x00007f009c12f000)**
    libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f009bd6a000)
    libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f009ba64000)
    libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f009b860000)
    /lib64/ld-linux-x86-64.so.2 (0x00007f009c982000)

**Comment by spolakh** [comment]
For me it's 

/usr/local/lib/luasandbox/modules/sax.so:
    libluasb.0.dylib (compatibility version 0.0.0, current version 5.1.5)
    /Users/vsterzhanov/lua_sandbox/release/src/libluasandbox.0.dylib (compatibility version 0.0.0, current version 0.9.0)
    /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1213.0.0)

Where you building it with my fork of luasb with additional CMAKE options?
https://github.com/Quadrocube/lua_sandbox

**Comment by trink** [comment]
Yeah, as discussed, the test for the sandbox build should part of symtseries build (since the sandbox is already passing a flag in)
