### ISSUE TITLE
Performance of sax_transform

### ISSUE THREAD

**Issue by spolakh** [Quadrocube/symtseries#21]
Check out whether dumping the normalization_buffer would be worse it
If yes, screw it and merge normalization with symbol estimation
+ (thanks trink for reminding) keep running average and std if operating with sts_window

**Comment by trink** [comment]
+1 Investigate if/where it can be improved.

SAX is currently used in conjunction with the circular buffer add() but at almost 6x slower for each operation it is the bottleneck.
- benchmark_cbuf_add() 3.11783e-07 seconds
- benchmark_bloom_filter_add() 3.83556e-07 seconds
- benchmark_hyperloglog_add() 2.72768e-07 seconds
- benchmark_cuckoo_filter_add() 3.27099e-07 seconds
- **benchmark_sax_add() 1.82977e-06 seconds**

**Comment by spolakh** [comment]
Switched to on-line mean and std estimation at #39, got 3x speedup on my benchmarks
