### ISSUE TITLE
Expect the sandbox output of a sax.window/word to be a human readable sax string

### ISSUE THREAD

**Issue by trink** [Quadrocube/symtseries#27]
The current window output is binary dump of a struct and the word output appears to be a Lua table.  I would prefer just the SAX string e.g. `ABBAC`.  

However, it would be nice to account for the cardinality so I am open to other suggestion. The iSAX binary representation isn't unambiguous since we aren't restricted to powers of 2.  The exponentiation representation wasn't bad but overkill on every symbol, maybe just tack it onto the end `ABBAC^4`?

**Comment by trink** [comment]
i.e. basically a tostring() without a round trip to the sandbox

**Comment by spolakh** [comment]
What would one expect from the output of window? Values + sax (if available) \ values + parameters  \ plain sax or nil if not available (this currently corresponds to actual __tostring)?

**Comment by trink** [comment]
Yeah, same output as the word
